[hydroqc2mqtt]
# nvfetcher doesn't pass down all options to nvchecker, so we can't use the native git or gitlab source
src.webpage = "https://gitlab.com/api/v4/projects/33246695/repository/tags?order_by=version&per_page=1"
src.regex = "\\d+\\.\\d+\\.\\d+"
fetch.docker  = "registry.gitlab.com/hydroqc/hydroqc2mqtt"
