# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  homeassistant = {
    pname = "homeassistant";
    version = "2024.4.0";
    src = dockerTools.pullImage {
      imageName = "ghcr.io/home-assistant/home-assistant";
      imageDigest = "sha256:2060bcda3ea90f601acf538d17e2e3139da50a5bd5cd9c56ec0a2cddba8b042d";
      sha256 = "sha256-l65/Tu4GDwCTM9homtA75yajwM4y0wjMFnYRYrNMi0A=";
      finalImageTag = "2024.4.0";
    };
  };
  hydroqc2mqtt = {
    pname = "hydroqc2mqtt";
    version = "1.2.0";
    src = dockerTools.pullImage {
      imageName = "registry.gitlab.com/hydroqc/hydroqc2mqtt";
      imageDigest = "sha256:dd616d3162367e549f270cb8dfb42ec9c105b3ccff96b9b921137869a9b6655d";
      sha256 = "sha256-vdkaBXwZ7qHG9hiC9gZmD2EOGAtCzSO7qmC48GPQRDU=";
      finalImageTag = "1.2.0";
    };
  };
  python-matter-server = {
    pname = "python-matter-server";
    version = "5.9.0";
    src = dockerTools.pullImage {
      imageName = "ghcr.io/home-assistant-libs/python-matter-server";
      imageDigest = "sha256:f857a093129151ac300cfc1d57bd6c3f65917e00d214d8d78e752174357e30ee";
      sha256 = "sha256-uo74AL1ZKwgph7xYY1rVVbBSZkbXDXXEkasVCRK+kps=";
      finalImageTag = "5.9.0";
    };
  };
  smartir = {
    pname = "smartir";
    version = "1.17.9";
    src = fetchFromGitHub {
      owner = "smartHomeHub";
      repo = "SmartIR";
      rev = "1.17.9";
      fetchSubmodules = false;
      sha256 = "sha256-E6TM761cuaeQzlbjA+oZ+wt5HTJAfkF2J3i4P1Wbuic=";
    };
  };
}
