# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  homeassistant = {
    pname = "homeassistant";
    version = "2024.2.0";
    src = dockerTools.pullImage {
      imageName = "ghcr.io/home-assistant/home-assistant";
      imageDigest = "sha256:2b55f63c70a556f8645c5ba240f5546ed85f151dd50b10f9ea9f2fb76cbdbf05";
      sha256 = "sha256-oDAOc5aqExrkOJ5gSst3dSH0y8LkFRJAAPfU+kOZjxM=";
      finalImageTag = "2024.2.0";
    };
  };
  hydroqc2mqtt = {
    pname = "hydroqc2mqtt";
    version = "1.2.0";
    src = dockerTools.pullImage {
      imageName = "registry.gitlab.com/hydroqc/hydroqc2mqtt";
      imageDigest = "sha256:dd616d3162367e549f270cb8dfb42ec9c105b3ccff96b9b921137869a9b6655d";
      sha256 = "sha256-vdkaBXwZ7qHG9hiC9gZmD2EOGAtCzSO7qmC48GPQRDU=";
      finalImageTag = "1.2.0";
    };
  };
  python-matter-server = {
    pname = "python-matter-server";
    version = "5.5.2";
    src = dockerTools.pullImage {
      imageName = "ghcr.io/home-assistant-libs/python-matter-server";
      imageDigest = "sha256:5a566583deddc0a8c8cb18fa48ca99317a8e863db0108a987fb80acc892b272e";
      sha256 = "sha256-8jgn0dGfFSQeKx0peJn5wK/gM6QQV/4G98pEwn449SQ=";
      finalImageTag = "5.5.2";
    };
  };
  smartir = {
    pname = "smartir";
    version = "1.17.9";
    src = fetchFromGitHub {
      owner = "smartHomeHub";
      repo = "SmartIR";
      rev = "1.17.9";
      fetchSubmodules = false;
      sha256 = "sha256-E6TM761cuaeQzlbjA+oZ+wt5HTJAfkF2J3i4P1Wbuic=";
    };
  };
}
