esphome:
  name: geeni-powerstrip

bk72xx:
  board: cb3s

# packages:
#   base: !include kickstart-base.yaml

wifi:
  domain: .local
  networks:
  - ssid: !secret ssid
    password: !secret wifi_password

ota:
  - platform: esphome
    password: !secret ota_password

api:
 encryption:
   key: !secret api_key

logger:

# select:
#   - platform: template
#     id: !extend pin
#     options:
#       - Select PIN
#       - P0 / UART2_TX / I2C2_SCL
#       # - P1 / UART2_RX / I2C2_SDA
#       - P6 / PWM0
#       - P7 / PWM1
#       - P8 / PWM2
#       - P9 / PWM3
#       - P10 / UART1_RX
#       - P11 / UART1_TX
#       - P14 / SCK
#       # - P15 / CS
#       # - P16 / MOSI
#       # - P17 / MISO
#       - P20 / I2C1_SCL / TCK
#       - P21 / I2C1_SDA / TMS
#       - P22 / TDI
#       - P23 / TDO / ADC3
#       - P24 / PWM4
#       - P26 / PWM5
#       # - P28

text_sensor:
  - platform: libretiny
    version:
      name: LibreTiny Version

switch:
  - platform: gpio
    id: switch_1
    name: Relay 1
    pin: P6
  - platform: gpio
    id: switch_2
    name: Relay 2
    pin: P24
  - platform: gpio
    id: switch_3
    name: Relay 3
    pin: P26
  - platform: gpio
    id: switch_4
    name: Relay 4
    pin: P8
  - platform: gpio
    id: switch_5
    name: Relay 5
    pin: P7
  - platform: gpio
    id: switch_6
    name: Relay 6
    pin: P9

binary_sensor:
  - platform: gpio
    id: binary_switch_all
    pin:
      number: P23
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle: switch_1
        - switch.toggle: switch_2
        - switch.toggle: switch_3
        - switch.toggle: switch_4
        - switch.toggle: switch_5
        - switch.toggle: switch_6

status_led:
  pin:
    number: P14
    inverted: true
