flakeArgs: {
  flake.aspects.shell-fish.homeManager =
    { config, pkgs, ... }:
    let
      inherit (flakeArgs.config) npins;
    in
    {
      programs.fish = {
        enable = true;
        package = pkgs.fish;
        interactiveShellInit = # fish
          ''

            # add completions generated by Home Manager to $fish_complete_path
            begin
              set -l joined (string join " " $fish_complete_path)
              set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
              set -l post_joined (string replace $prev_joined "" $joined)
              set -l prev (string split " " (string trim $prev_joined))
              set -l post (string split " " (string trim $post_joined))
              set fish_complete_path $prev "${config.xdg.dataHome}/fish/home-manager_generated_completions" $post
            end

            set PATH ~/.nix-profile/bin /nix/var/nix/profiles/default/bin ~/.cargo/bin ~/.deno/bin $GOPATH/bin ~/.npm-global-packages/bin $PATH

            # Setup terminal, and turn on colors
            set -x TERM xterm-256color

            # Enable color in grep
            # set -x GREP_OPTIONS '--color=auto'
            set -x GREP_COLOR '3;33'

            # language settings
            set -x LANG en_US.UTF-8
            set -x LC_CTYPE "en_US.UTF-8"
            set -x LC_MESSAGES "en_US.UTF-8"
            set -x LC_COLLATE C

            set EDITOR nvim

            # Enable direnv
            if command -v direnv &>/dev/null
                eval (direnv hook fish)
            end

            # Enable zoxice `z` (https://github.com/ajeetdsouza/zoxide)
            if command -v zoxide &>/dev/null
              zoxide init fish | source
            end

            #any-nix-shell fish --info-right | source

            set -g theme_color_scheme "Catppuccin Mocha"

            bind -M insert \cg '${./fzf-ripgrep.sh}'
            bind -M insert \cn 'commandline -i (fzf-nix)'
          '';
        functions = {
          o = ''
            if test (count $argv) -eq 0
              open .
            else
              open $argv
            end
          '';

          hm = ''
            pushd ~/dotfiles
            home-manager switch --flake .
            popd
          '';
        };
        plugins = [
          {
            name = "bobthefish";
            src = npins.theme-bobthefish;
          }
          {
            name = "fish-docker";
            src = npins.fish-docker;
          }
          {
            name = "cattpuccin";
            src = npins.catppuccin-fish;
          }
          {
            name = "fzf-fish";
            src = npins.fzf-fish;
          }
          {
            # Syncs fish_completion_path from XDG_DATA_DIR, this makes completions
            # work with direnv (if the package is added to nativeBuildInputs)
            name = "fish-completion-sync";
            src = npins.fish-completion-sync;
          }
          {
            name = "bass";
            src = pkgs.fishPlugins.bass;
          }
        ];

        shellAliases = {
          v = "nvim";
          l = "exa";
          fz = "fzf --preview 'bat --style=numbers --color=always --line-range :500 {}'";
          cdg = "cd (git rev-parse --show-toplevel)";
          svim = "nvim +'SLoad!'";
          h = "hctl";
        };

        shellAbbrs = {
          s = "ssh";

          # git
          g = "git";
          gs = "git status";
          ga = "git add";
          gl = "git log --pretty=format:'%C(yellow)%h %Cred%ar %Cblue%an%Cgreen%d %Creset%s' --date=short";
          gt = "git tag --format='%(creatordate:short)%09%(refname:strip=2)' --sort=creatordate | tail -n10";
          gd = "git diff";
          gp = "git pull";
          gps = "git push";
          gcm = "git commit";
          gco = "git checkout";
          gcl = "git clone";
          gri = "git rebase -i --committer-date-is-author-date --autostash";

          d = "docker";
          k = "kubectl";
          b = "bat";

          nr =
            if pkgs.stdenv.isLinux then
              "nix run ~/dotfiles#nixosConfigurations.(hostname).pkgs.(fzf-nix)"
            else
              "nix run nixpkgs#(fzf-nix)";
          ns =
            if pkgs.stdenv.isLinux then
              "nix shell ~/dotfiles#nixosConfigurations.(hostname).pkgs.(fzf-nix)"
            else
              "nix shell nixpkgs#(fzf-nix)";

          ".." = "cd ..";
          "..." = "cd ../..";
          "...." = "cd ../../..";
          "....." = "cd ../../../..";

          findport = "sudo lsof -iTCP -sTCP:LISTEN -n -P | grep";
        };
      };

      programs.starship = {
        enable = true;
        settings = {
          gcloud = {
            disabled = true;
          };
          nix_shell = {
            disabled = true;
          };
          package = {
            disabled = true;
          };

          env_var.NONO_CAP_FILE = {
            symbol = "󰒃 ";
            format = "[$symbol]($style)";
            style = "bold red";
          };
        };
      };
    };
}
