- id: '1671602514913'
  alias: Morning Heat
  description: Turns on heating in the morning
  trigger:
  - platform: time
    at: 07:00:00
  condition: []
  action:
  - service: climate.set_temperature
    data:
      hvac_mode: heat
      temperature: 24
  mode: single
- id: '1707101362132'
  alias: HQ Credits Hivernaux
  description: ''
  use_blueprint:
    path: hydroqc/hydroqc-winter-credits.yaml
    input:
      pre_heat_start_action:
      - parallel:
        - service: climate.set_temperature
          metadata: {}
          data:
            temperature: 22
            hvac_mode: heat
          target:
            entity_id: climate.hallway
      critical_peak_start_action:
      - parallel:
        - service: climate.set_temperature
          metadata: {}
          data:
            temperature: 19
            hvac_mode: heat
          target:
            entity_id: climate.hallway
        - service: climate.set_temperature
          metadata: {}
          data:
            hvac_mode: 'off'
            temperature: 22
          target:
            entity_id: climate.heat_pump
      critical_peak_end_action:
      - parallel:
        - service: climate.set_temperature
          metadata: {}
          data:
            temperature: 21
            hvac_mode: heat
          target:
            entity_id: climate.hallway
        - service: climate.set_temperature
          metadata: {}
          data:
            hvac_mode: 'off'
            temperature: 22
          target:
            entity_id: climate.heat_pump
- id: '1707101449999'
  alias: Turn On Living Room TV with WakeOnLan
  trigger:
  - platform: webostv.turn_on
    entity_id: media_player.lg_webos_smart_tv
  action:
  - service: wake_on_lan.send_magic_packet
    data:
      mac: 64:E4:A5:E2:38:F4
- id: '1716259925750'
  alias: Turn off ac at 1am
  description: ''
  trigger:
  - platform: time
    at: 01:00:00
  condition: []
  action:
  - service: climate.set_hvac_mode
    metadata: {}
    data:
      hvac_mode: 'off'
    target:
      entity_id: climate.heat_pump
  mode: single
